# Generated by Django 5.2.17 on 2026-09-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zkbchecker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcludedShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_type_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(help_text='For readability only, not used in logic.', max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='general',
            options={'default_permissions': (), 'managed': False, 'permissions': (('basic_access', 'Can access this app'), ('manage_config', 'Can manage suspicious alliances/corps and excluded ships'))},
        ),
        migrations.CreateModel(
            name='SuspiciousEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.PositiveIntegerField()),
                ('entity_type', models.CharField(choices=[('alliance', 'Alliance'), ('corporation', 'Corporation')], max_length=20)),
                ('label', models.CharField(help_text='Displayed in results when this entity is matched.', max_length=255)),
            ],
            options={
                'ordering': ['label'],
                'constraints': [models.UniqueConstraint(fields=('entity_id', 'entity_type'), name='unique_entity_id_per_type')],
            },
        ),
    ]
